CREATE TABLE public.schedule (
	"scheduleDate" date NOT NULL,
	"scheduleTitle" varchar(255) NOT NULL,
	"scheduleId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"scheduleDescription" varchar(255) NOT NULL,
	CONSTRAINT "PK_e2f8b8dde7d240896cd58c669a2" PRIMARY KEY ("scheduleId")
);